include_defs('//bucklets/maven_jar.bucklet')

VER = '2.13.3'
REPO = MAVEN_CENTRAL

maven_jar(
  name = 'plugin-api',
  id = 'com.google.gerrit:gerrit-plugin-api:' + VER,
  sha1 = '78df190269b0d5a4bc4f61ab3a66a49252b779eb',
  attach_source = False,
  repository = REPO,
  license = 'Apache2.0',
)

